### ISSUE TITLE
Moving an example in another location throws an error

### ISSUE THREAD

**Issue by Melchyore** [comunica/examples#11]
Hello!

I don't know if I'm doing something wrong, but I'm cloning this repository on my machine, then I run ```yarn install```. I go then to the actor-observe-rdf-dereference example and I run ```node bin/run``` and it works without any problem.
Now I want to edit the example and to deploy it as a separate NPM package. So, I take the directory actor-observe-rdf-dereference and I move it to another location on my machine, and I run ```yarn install``` to install all Comunica's dependencies. But running ```node bin/run``` throws the following error:
![image](https://user-images.githubusercontent.com/6685773/119488848-4c9d8f80-bd5b-11eb-8694-1c927628b64b.png)

@rubensworks you told me that it may be caused by outdated packages on Gitter but if was the cause of the issue, I think it shouldn't work at all, should it?

**Comment by rubensworks** [comment]
> you told me that it may be caused by outdated packages on Gitter but if was the cause of the issue, I think it shouldn't work at all, should it?

You're right, it looks like the outdated dependencies aren't a problem (but they are causing the warnings).

I suspect the config loader is tripping over this line: https://github.com/comunica/examples/blob/master/packages/actor-observe-rdf-dereference/config/config-default.json#L8
Could you try removing that line?

In any case, it _should_ also work with that line. So if it works when removing that line, then there's a bug in [Components.js](https://github.com/LinkedSoftwareDependencies/Components.js).

**Comment by Melchyore** [comment]
@rubensworks thanks for your answer. Removing that line causes another error:

```
Detected fatal error. Generated 'componentsjs-error-state.json' with more information.
(node:9512) UnhandledPromiseRejectionWarning: Error: Cannot find module 'example-actor-rdf-dereference'
```

**Comment by rubensworks** [comment]
Are you sure you have a `package.json` with `name` set to `example-actor-rdf-dereference`?

**Comment by Melchyore** [comment]
Yes, it was not the problem. I was using a custom build directory for Typescript compiled files but that was not causing the issue. I removed the build directory and left the compiled files with the original ones (in the same directory), it was still not working.

Finally, removing the line 8 from the config-default.json file (with compiled files in the same directories), as you suggested me resolved the problem... so there's a problem with Components.js I think.
